-- 修復匯率資料
-- RATE_TO_TWD 表示：1 單位該幣別 = RATE_TO_TWD TWD
-- 例如：1 USD = 31.25 TWD，所以 USD 的 RATE_TO_TWD = 31.25

-- 更新 USD 匯率（1 USD = 31.25 TWD）
UPDATE CURRENCIES SET RATE_TO_TWD = 31.250000, LAST_UPDATE = SYSDATE WHERE CURRENCY_CODE = 'USD';

-- 更新 EUR 匯率（1 EUR = 34.48 TWD）
UPDATE CURRENCIES SET RATE_TO_TWD = 34.480000, LAST_UPDATE = SYSDATE WHERE CURRENCY_CODE = 'EUR';

-- 更新 JPY 匯率（1 JPY = 0.22 TWD）
UPDATE CURRENCIES SET RATE_TO_TWD = 0.220000, LAST_UPDATE = SYSDATE WHERE CURRENCY_CODE = 'JPY';

-- 更新 CNY 匯率（1 CNY = 4.35 TWD）
UPDATE CURRENCIES SET RATE_TO_TWD = 4.350000, LAST_UPDATE = SYSDATE WHERE CURRENCY_CODE = 'CNY';

-- 確認 TWD 匯率為 1
UPDATE CURRENCIES SET RATE_TO_TWD = 1.000000, LAST_UPDATE = SYSDATE WHERE CURRENCY_CODE = 'TWD';

COMMIT;

-- 驗證匯率
SELECT CURRENCY_CODE, RATE_TO_TWD, LAST_UPDATE FROM CURRENCIES ORDER BY CURRENCY_CODE;


