-- 初始化幣別資料
-- 注意：Oracle 需要使用不同的方式初始化資料，這裡僅作為參考

-- 插入幣別資料
-- RATE_TO_TWD 表示：1 單位該幣別 = RATE_TO_TWD TWD
-- 例如：1 USD = 31.25 TWD，所以 USD 的 RATE_TO_TWD = 31.25
INSERT INTO CURRENCIES (CURRENCY_CODE, RATE_TO_TWD, LAST_UPDATE) VALUES ('TWD', 1.000000, SYSDATE);
INSERT INTO CURRENCIES (CURRENCY_CODE, RATE_TO_TWD, LAST_UPDATE) VALUES ('USD', 31.250000, SYSDATE);
INSERT INTO CURRENCIES (CURRENCY_CODE, RATE_TO_TWD, LAST_UPDATE) VALUES ('EUR', 34.480000, SYSDATE);
INSERT INTO CURRENCIES (CURRENCY_CODE, RATE_TO_TWD, LAST_UPDATE) VALUES ('JPY', 0.220000, SYSDATE);
INSERT INTO CURRENCIES (CURRENCY_CODE, RATE_TO_TWD, LAST_UPDATE) VALUES ('CNY', 4.350000, SYSDATE);

-- 插入範例訂單資料
-- 注意：ORDER_ID 會由 SEQUENCE 自動產生
INSERT INTO ORDERS (USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES ('user1', 1000.00, 'USD', 'PENDING', 0.00, 1000.00, SYSDATE, SYSDATE);

INSERT INTO ORDERS (USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES ('user2', 5000.00, 'TWD', 'CONFIRMED', 10.00, 4500.00, SYSDATE, SYSDATE);

INSERT INTO ORDERS (USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES ('user3', 200.00, 'EUR', 'COMPLETED', 5.00, 190.00, SYSDATE, SYSDATE);

