-- Oracle 資料庫 Schema 建立腳本

-- 建立幣別表
CREATE TABLE CURRENCIES (
    CURRENCY_CODE VARCHAR2(3) PRIMARY KEY,
    RATE_TO_TWD NUMBER(19, 6) NOT NULL,
    LAST_UPDATE TIMESTAMP
);

-- 建立訂單表
CREATE TABLE ORDERS (
    ORDER_ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL,
    AMOUNT NUMBER(19, 2) NOT NULL,
    CURRENCY VARCHAR2(3) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'PENDING',
    DISCOUNT NUMBER(5, 2) DEFAULT 0,
    FINAL_AMOUNT NUMBER(19, 2),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

-- 建立訂單序號
CREATE SEQUENCE ORDER_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 建立索引
CREATE INDEX IDX_ORDERS_USERNAME ON ORDERS(USERNAME);
CREATE INDEX IDX_ORDERS_STATUS ON ORDERS(STATUS);
CREATE INDEX IDX_ORDERS_CURRENCY ON ORDERS(CURRENCY);

-- 建立 CREATED_AT 索引（用於排序，提升查詢效能）
CREATE INDEX IDX_ORDERS_CREATED_AT ON ORDERS(CREATED_AT DESC);

-- 建立函數索引（用於 ORDER_ID 字串搜尋，大幅提升 LIKE 查詢效能）
-- 這個索引會將 ORDER_ID 轉換為字串後建立索引，讓 LIKE '%...%' 查詢可以使用索引
CREATE INDEX IDX_ORDERS_ORDER_ID_STR ON ORDERS(TO_CHAR(ORDER_ID));

-- ============================================
-- 用戶和權限管理相關表
-- ============================================

-- 建立角色表
CREATE TABLE ROLES (
    ROLE_ID NUMBER PRIMARY KEY,
    ROLE_NAME VARCHAR2(50) NOT NULL UNIQUE
);

-- 建立角色序號
CREATE SEQUENCE ROLE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 建立用戶表
CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    ENABLED NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

-- 建立用戶序號
CREATE SEQUENCE USER_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 建立用戶角色關聯表
CREATE TABLE USER_ROLES (
    USER_ID NUMBER NOT NULL,
    ROLE_ID NUMBER NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_USER_ROLES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_USER_ROLES_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID) ON DELETE CASCADE
);

-- 建立索引
CREATE INDEX IDX_USERS_USERNAME ON USERS(USERNAME);
CREATE INDEX IDX_USERS_EMAIL ON USERS(EMAIL);
CREATE INDEX IDX_USERS_ENABLED ON USERS(ENABLED);
CREATE INDEX IDX_ROLES_ROLE_NAME ON ROLES(ROLE_NAME);
CREATE INDEX IDX_USER_ROLES_USER_ID ON USER_ROLES(USER_ID);
CREATE INDEX IDX_USER_ROLES_ROLE_ID ON USER_ROLES(ROLE_ID);

-- ============================================
-- 選單管理相關表
-- ============================================

-- 建立選單表
CREATE TABLE MENUS (
    MENU_ID NUMBER PRIMARY KEY,
    MENU_KEY VARCHAR2(50) NOT NULL UNIQUE,
    LABEL VARCHAR2(100) NOT NULL,
    ICON VARCHAR2(50),
    ROUTE VARCHAR2(50) NOT NULL,
    SORT_ORDER NUMBER DEFAULT 0,
    ENABLED NUMBER(1) DEFAULT 1 NOT NULL
);

-- 建立選單序號
CREATE SEQUENCE MENU_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 建立選單角色關聯表
CREATE TABLE MENU_ROLES (
    MENU_ID NUMBER NOT NULL,
    ROLE_ID NUMBER NOT NULL,
    PRIMARY KEY (MENU_ID, ROLE_ID),
    CONSTRAINT FK_MENU_ROLES_MENU FOREIGN KEY (MENU_ID) REFERENCES MENUS(MENU_ID) ON DELETE CASCADE,
    CONSTRAINT FK_MENU_ROLES_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID) ON DELETE CASCADE
);

-- 建立索引
CREATE INDEX IDX_MENUS_MENU_KEY ON MENUS(MENU_KEY);
CREATE INDEX IDX_MENUS_ENABLED ON MENUS(ENABLED);
CREATE INDEX IDX_MENUS_SORT_ORDER ON MENUS(SORT_ORDER);
CREATE INDEX IDX_MENU_ROLES_MENU_ID ON MENU_ROLES(MENU_ID);
CREATE INDEX IDX_MENU_ROLES_ROLE_ID ON MENU_ROLES(ROLE_ID);
