-- Oracle 資料庫 Schema 建立腳本

-- 建立幣別表
CREATE TABLE CURRENCIES (
    CURRENCY_CODE VARCHAR2(3) PRIMARY KEY,
    RATE_TO_TWD NUMBER(19, 6) NOT NULL,
    LAST_UPDATE TIMESTAMP
);

-- 建立訂單表
CREATE TABLE ORDERS (
    ORDER_ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL,
    AMOUNT NUMBER(19, 2) NOT NULL,
    CURRENCY VARCHAR2(3) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'PENDING',
    DISCOUNT NUMBER(5, 2) DEFAULT 0,
    FINAL_AMOUNT NUMBER(19, 2),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

-- 建立訂單序號
CREATE SEQUENCE ORDER_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 建立索引
CREATE INDEX IDX_ORDERS_USERNAME ON ORDERS(USERNAME);
CREATE INDEX IDX_ORDERS_STATUS ON ORDERS(STATUS);
CREATE INDEX IDX_ORDERS_CURRENCY ON ORDERS(CURRENCY);

