-- 插入 70 筆測試訂單資料
-- 注意：ORDER_ID 使用 ORDER_SEQ.NEXTVAL 由 SEQUENCE 產生
-- FINAL_AMOUNT = AMOUNT - (AMOUNT * DISCOUNT / 100)

-- 批次 1: 使用者 user1 的訂單 (10筆)
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user1', 1500.00, 'USD', 'PENDING', 0.00, 1500.00, SYSDATE - 70, SYSDATE - 70);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user1', 3200.50, 'TWD', 'CONFIRMED', 5.00, 3040.48, SYSDATE - 69, SYSDATE - 69);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user1', 850.75, 'EUR', 'COMPLETED', 10.00, 765.68, SYSDATE - 68, SYSDATE - 68);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user1', 50000.00, 'JPY', 'PENDING', 0.00, 50000.00, SYSDATE - 67, SYSDATE - 67);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user1', 2500.00, 'CNY', 'CONFIRMED', 15.00, 2125.00, SYSDATE - 66, SYSDATE - 66);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user1', 980.25, 'USD', 'CANCELLED', 0.00, 980.25, SYSDATE - 65, SYSDATE - 65);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user1', 4500.00, 'TWD', 'COMPLETED', 8.00, 4140.00, SYSDATE - 64, SYSDATE - 64);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user1', 1200.00, 'EUR', 'PENDING', 0.00, 1200.00, SYSDATE - 63, SYSDATE - 63);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user1', 75000.00, 'JPY', 'CONFIRMED', 12.00, 66000.00, SYSDATE - 62, SYSDATE - 62);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user1', 3800.00, 'CNY', 'COMPLETED', 5.00, 3610.00, SYSDATE - 61, SYSDATE - 61);

-- 批次 2: 使用者 user2 的訂單 (10筆)
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user2', 2200.00, 'USD', 'CONFIRMED', 0.00, 2200.00, SYSDATE - 60, SYSDATE - 60);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user2', 6800.00, 'TWD', 'PENDING', 10.00, 6120.00, SYSDATE - 59, SYSDATE - 59);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user2', 950.50, 'EUR', 'COMPLETED', 0.00, 950.50, SYSDATE - 58, SYSDATE - 58);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user2', 120000.00, 'JPY', 'CONFIRMED', 8.00, 110400.00, SYSDATE - 57, SYSDATE - 57);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user2', 1500.00, 'CNY', 'PENDING', 0.00, 1500.00, SYSDATE - 56, SYSDATE - 56);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user2', 3500.00, 'USD', 'CANCELLED', 5.00, 3325.00, SYSDATE - 55, SYSDATE - 55);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user2', 9200.00, 'TWD', 'COMPLETED', 15.00, 7820.00, SYSDATE - 54, SYSDATE - 54);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user2', 1800.00, 'EUR', 'CONFIRMED', 0.00, 1800.00, SYSDATE - 53, SYSDATE - 53);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user2', 95000.00, 'JPY', 'PENDING', 10.00, 85500.00, SYSDATE - 52, SYSDATE - 52);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user2', 4200.00, 'CNY', 'COMPLETED', 0.00, 4200.00, SYSDATE - 51, SYSDATE - 51);

-- 批次 3: 使用者 user3 的訂單 (10筆)
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user3', 1100.00, 'USD', 'COMPLETED', 0.00, 1100.00, SYSDATE - 50, SYSDATE - 50);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user3', 5400.00, 'TWD', 'PENDING', 12.00, 4752.00, SYSDATE - 49, SYSDATE - 49);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user3', 750.25, 'EUR', 'CONFIRMED', 0.00, 750.25, SYSDATE - 48, SYSDATE - 48);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user3', 80000.00, 'JPY', 'CANCELLED', 0.00, 80000.00, SYSDATE - 47, SYSDATE - 47);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user3', 2800.00, 'CNY', 'COMPLETED', 7.00, 2604.00, SYSDATE - 46, SYSDATE - 46);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user3', 1900.00, 'USD', 'PENDING', 0.00, 1900.00, SYSDATE - 45, SYSDATE - 45);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user3', 7600.00, 'TWD', 'CONFIRMED', 20.00, 6080.00, SYSDATE - 44, SYSDATE - 44);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user3', 1300.00, 'EUR', 'COMPLETED', 0.00, 1300.00, SYSDATE - 43, SYSDATE - 43);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user3', 110000.00, 'JPY', 'PENDING', 15.00, 93500.00, SYSDATE - 42, SYSDATE - 42);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'user3', 3600.00, 'CNY', 'CONFIRMED', 0.00, 3600.00, SYSDATE - 41, SYSDATE - 41);

-- 批次 4: 使用者 alice 的訂單 (10筆)
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'alice', 2800.00, 'USD', 'CONFIRMED', 0.00, 2800.00, SYSDATE - 40, SYSDATE - 40);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'alice', 8900.00, 'TWD', 'COMPLETED', 5.00, 8455.00, SYSDATE - 39, SYSDATE - 39);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'alice', 1650.00, 'EUR', 'PENDING', 0.00, 1650.00, SYSDATE - 38, SYSDATE - 38);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'alice', 130000.00, 'JPY', 'CONFIRMED', 10.00, 117000.00, SYSDATE - 37, SYSDATE - 37);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'alice', 5100.00, 'CNY', 'CANCELLED', 0.00, 5100.00, SYSDATE - 36, SYSDATE - 36);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'alice', 3200.00, 'USD', 'COMPLETED', 8.00, 2944.00, SYSDATE - 35, SYSDATE - 35);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'alice', 11200.00, 'TWD', 'PENDING', 0.00, 11200.00, SYSDATE - 34, SYSDATE - 34);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'alice', 2100.00, 'EUR', 'CONFIRMED', 12.00, 1848.00, SYSDATE - 33, SYSDATE - 33);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'alice', 140000.00, 'JPY', 'COMPLETED', 0.00, 140000.00, SYSDATE - 32, SYSDATE - 32);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'alice', 6400.00, 'CNY', 'PENDING', 6.00, 6016.00, SYSDATE - 31, SYSDATE - 31);

-- 批次 5: 使用者 bob 的訂單 (10筆)
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'bob', 4100.00, 'USD', 'PENDING', 0.00, 4100.00, SYSDATE - 30, SYSDATE - 30);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'bob', 15300.00, 'TWD', 'CONFIRMED', 18.00, 12546.00, SYSDATE - 29, SYSDATE - 29);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'bob', 2400.00, 'EUR', 'COMPLETED', 0.00, 2400.00, SYSDATE - 28, SYSDATE - 28);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'bob', 160000.00, 'JPY', 'PENDING', 0.00, 160000.00, SYSDATE - 27, SYSDATE - 27);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'bob', 7200.00, 'CNY', 'CANCELLED', 5.00, 6840.00, SYSDATE - 26, SYSDATE - 26);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'bob', 5500.00, 'USD', 'CONFIRMED', 10.00, 4950.00, SYSDATE - 25, SYSDATE - 25);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'bob', 18400.00, 'TWD', 'COMPLETED', 0.00, 18400.00, SYSDATE - 24, SYSDATE - 24);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'bob', 2900.00, 'EUR', 'PENDING', 15.00, 2465.00, SYSDATE - 23, SYSDATE - 23);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'bob', 170000.00, 'JPY', 'CONFIRMED', 0.00, 170000.00, SYSDATE - 22, SYSDATE - 22);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'bob', 8300.00, 'CNY', 'COMPLETED', 8.00, 7636.00, SYSDATE - 21, SYSDATE - 21);

-- 批次 6: 使用者 charlie 的訂單 (10筆)
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'charlie', 6200.00, 'USD', 'COMPLETED', 0.00, 6200.00, SYSDATE - 20, SYSDATE - 20);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'charlie', 21500.00, 'TWD', 'PENDING', 0.00, 21500.00, SYSDATE - 19, SYSDATE - 19);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'charlie', 3500.00, 'EUR', 'CONFIRMED', 20.00, 2800.00, SYSDATE - 18, SYSDATE - 18);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'charlie', 180000.00, 'JPY', 'CANCELLED', 0.00, 180000.00, SYSDATE - 17, SYSDATE - 17);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'charlie', 9400.00, 'CNY', 'COMPLETED', 0.00, 9400.00, SYSDATE - 16, SYSDATE - 16);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'charlie', 7100.00, 'USD', 'PENDING', 12.00, 6248.00, SYSDATE - 15, SYSDATE - 15);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'charlie', 24600.00, 'TWD', 'CONFIRMED', 0.00, 24600.00, SYSDATE - 14, SYSDATE - 14);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'charlie', 4200.00, 'EUR', 'COMPLETED', 5.00, 3990.00, SYSDATE - 13, SYSDATE - 13);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'charlie', 190000.00, 'JPY', 'PENDING', 10.00, 171000.00, SYSDATE - 12, SYSDATE - 12);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'charlie', 10500.00, 'CNY', 'CONFIRMED', 0.00, 10500.00, SYSDATE - 11, SYSDATE - 11);

-- 批次 7: 使用者 david 的訂單 (10筆)
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'david', 8200.00, 'USD', 'CONFIRMED', 0.00, 8200.00, SYSDATE - 10, SYSDATE - 10);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'david', 27800.00, 'TWD', 'COMPLETED', 25.00, 20850.00, SYSDATE - 9, SYSDATE - 9);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'david', 5100.00, 'EUR', 'PENDING', 0.00, 5100.00, SYSDATE - 8, SYSDATE - 8);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'david', 200000.00, 'JPY', 'CONFIRMED', 0.00, 200000.00, SYSDATE - 7, SYSDATE - 7);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'david', 11600.00, 'CNY', 'CANCELLED', 8.00, 10672.00, SYSDATE - 6, SYSDATE - 6);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'david', 9300.00, 'USD', 'COMPLETED', 15.00, 7905.00, SYSDATE - 5, SYSDATE - 5);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'david', 30900.00, 'TWD', 'PENDING', 0.00, 30900.00, SYSDATE - 4, SYSDATE - 4);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'david', 6000.00, 'EUR', 'CONFIRMED', 0.00, 6000.00, SYSDATE - 3, SYSDATE - 3);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'david', 210000.00, 'JPY', 'COMPLETED', 12.00, 184800.00, SYSDATE - 2, SYSDATE - 2);
INSERT INTO ORDERS (ORDER_ID, USERNAME, AMOUNT, CURRENCY, STATUS, DISCOUNT, FINAL_AMOUNT, CREATED_AT, UPDATED_AT) 
VALUES (ORDER_SEQ.NEXTVAL, 'david', 12700.00, 'CNY', 'PENDING', 0.00, 12700.00, SYSDATE - 1, SYSDATE - 1);

